apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-go-pubsub-pub
  labels:
    app: dapr-go-pubsub-pub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dapr-go-pubsub-pub
  template:
    metadata:
      labels:
        app: dapr-go-pubsub-pub
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "dapr-go-pubsub-pub"
        dapr.io/enable-api-logging: "true"
        dapr.io/app-port: "6002"
    spec:
      containers:
        - name: dapr-go-pubsub-pub
          image: gongxh/dapr-go-pubsub-pub@sha256:b3030b12e3531e9c2aaf83b9e038de37d4ab0ed2185cabe9a3465ef4361bbc38
          # env:
          #   - name: WORKFLOW_NAME
          #     value: "dapr-workflow"
