apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-go-pubsub-sub
  labels:
    app: dapr-go-pubsub-sub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dapr-go-pubsub-sub
  template:
    metadata:
      labels:
        app: dapr-go-pubsub-sub
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "dapr-go-pubsub-sub"
        dapr.io/app-port: "6002"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
        - name: dapr-go-pubsub-sub
          image: gongxh/dapr-go-pubsub-sub@sha256:d3118281ab468767b8e11aa48b5eeb5cf0cac1b81d01011b28d908a9902eff0b
          # env:
          #   - name: WORKFLOW_NAME
          #     value: "dapr-workflow"
