apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: pubsub-redis
spec:
  topic: orders
  routes: 
    default: /checkout
  pubsubname: pubsub-redis
# scopes:
# - dapr-go-pubsub-sub
# - dapr-go-pubsub-sub1
# - dapr-go-pubsub-pub