apiVersion: core.openfunction.io/v1beta1
kind: Function
metadata:
  name: function-dapr-state
spec:
  version: "v2.0.0"
  image: "gongxh/function-dapr-state:latest"
  imageCredentials:
    name: push-secret
  port: 8080 # default to 8080
  serving:
    annotations:
      openfunction.io/enable-dapr: "true"
      openfunction.io/dapr-service-mode: "standalone"
    template:
      containers:
        - name: function # DO NOT change this
          imagePullPolicy: IfNotPresent
    runtime: "knative"