apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-redis-master-0
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/redis-master-0
---
apiVersion: v1
kind: PersistentVolume

metadata:
  name: redis-data-redis-replicas-0
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/redis-replicas-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-redis-replicas-1
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/redis-replicas-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-redis-replicas-2
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/redis-replicas-2
