apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-distribute-workflow-order
  labels:
    app: dapr-distribute-workflow-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dapr-distribute-workflow-order
  template:
    metadata:
      labels:
        app: dapr-distribute-workflow-order
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "dapr-distribute-workflow-order"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
        - name: dapr-distribute-workflow-order
          image: gongxh/dapr-distribute-workflow-order@sha256:0801df135360bc611a086de44355a3a2849d4029bd006bb5a119ec87a6c2d1ed
          # env:
          #   - name: WORKFLOW_NAME
          #     value: "dapr-workflow"
