apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-distribute-workflow-order
  labels:
    app: dapr-distribute-workflow-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dapr-distribute-workflow-order
  template:
    metadata:
      labels:
        app: dapr-distribute-workflow-order
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "dapr-distribute-workflow-order"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
        - name: dapr-distribute-workflow-order
          image: gongxh/dapr-distribute-workflow-order@sha256:8f5e85a0ac233b0c1275df2a0f9d2e34ce279dc7837b38296b315b45cca18002
          # env:
          #   - name: WORKFLOW_NAME
          #     value: "dapr-workflow"
