apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-distribute-workflow-inventory
  labels:
    app: dapr-distribute-workflow-inventory
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dapr-distribute-workflow-inventory
  template:
    metadata:
      labels:
        app: dapr-distribute-workflow-inventory
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "dapr-distribute-workflow-inventory"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
        - name: dapr-distribute-workflow-inventory
          image: gongxh/dapr-distribute-workflow-inventory@sha256:b3c51f816ae54a31ba90ad40b4ef526eaeac768bc898cd9150ef33edc555f6f4
          # env:
          #   - name: WORKFLOW_NAME
          #     value: "dapr-workflow"
