apiVersion: core.openfunction.io/v1beta1
kind: Function
metadata:
  name: autoscaling-subscriber
spec:
  version: "v2.0.0"
  image: gongxh/function-dapr-sub:latest
  imageCredentials:
    name: push-secret
  serving:
    runtime: "async"
    scaleOptions:
      keda:
        scaledObject:
          pollingInterval: 15
          minReplicaCount: 0
          maxReplicaCount: 10
          cooldownPeriod: 60
          advanced:
            horizontalPodAutoscalerConfig:
              behavior:
                scaleDown:
                  stabilizationWindowSeconds: 45
                  policies:
                  - type: Percent
                    value: 50
                    periodSeconds: 15
                scaleUp:
                  stabilizationWindowSeconds: 0
    triggers:
      - type: kafka
        metadata:
          topic: "function-dapr-pubsub-topic"
          bootstrapServers: kafka-openfunction-demo-kafka-brokers.default.svc.cluster.local:9092
          consumerGroup: autoscaling-subscriber
          lagThreshold: "20"
    template:
      containers:
        - name: function # DO NOT change this
          imagePullPolicy: IfNotPresent
    inputs:
      - name: producer
        component: kafka-server
        topic: "function-dapr-pubsub-topic"
    pubsub:
      kafka-server:
        type: pubsub.kafka
        version: v1
        metadata:
          - name: brokers
            value: "kafka-openfunction-demo-kafka-brokers:9092"
          - name: authRequired
            value: "false"
          - name: allowedTopics
            value: "function-dapr-pubsub-topic"
          - name: consumerID
            value: "autoscaling-subscriber"
