apiVersion: apps/v1
kind: Deployment
metadata:
  name: call-workflow-order-processor
  labels:
    app: call-workflow-order-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: call-workflow-order-processor
  template:
    metadata:
      labels:
        app: call-workflow-order-processor
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "call-workflow-order-processor"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
        - name: dapr-workflow-order-processor
          image: gongxh/dapr-call-workflow-order-processor@sha256:00ad1192299efc9c8f39834aee0056e6ee96e9aeaa158e631aea72d796ab9c7d
          env:
            - name: WORKFLOW_NAME
              value: "dapr-workflow"
