kind: Service
apiVersion: v1
metadata:
  name: dapr-call-workflow-front
  labels:
    app: dapr-call-workflow-front
spec:
  selector:
    app: dapr-call-workflow-front
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-call-workflow-front
  labels:
    app: dapr-call-workflow-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dapr-call-workflow-front
  template:
    metadata:
      labels:
        app: dapr-call-workflow-front
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "dapr-call-workflow-front"
        dapr.io/app-port: "3000"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
      - name: dapr-call-workflow-front
        image: gongxh/dapr-call-workflow-front@sha256:317bb9ea7ded1df76db2ef77cef07a0f3d84cc591e85e1c9bafa2f7af66ad155
        env:
        - name: APP_PORT
          value: "3000"
        ports:
        - containerPort: 3000